#!/usr/bin/env python3

import re
from datetime import datetime, timedelta

from request_lib import request

# community maintained feed of amazon prime free games, see
# https://github.com/eikowagenknecht/lootscraper
AMAZON_GAMES_FEED_URL = "https://feed.eikowagenknecht.com/lootscraper_amazon_game.xml"
AMAZON_ID_PREFIX = "amazon-"
AMAZON_PLATFORM_NAME = "Amazon Prime"

# decky's bundled python does not ship xml.etree, so the feed is parsed with
# regular expressions instead; the feed is machine generated by lootscraper
# so its structure is stable
_ENTRY_PATTERN = re.compile(r"<entry(?:\s[^>]*)?>(.*?)</entry>", re.DOTALL)
_LINK_PATTERN = re.compile(r'<(?:\w+:)?link[^>]*href="([^"]*)"')
_IMG_PATTERN = re.compile(r'<(?:\w+:)?img[^>]*src="([^"]*)"')
_LIST_ITEM_PATTERN = re.compile(r"<(?:\w+:)?li>(.*?)</(?:\w+:)?li>", re.DOTALL)
_TAG_PATTERN = re.compile(r"<[^>]+>")
# feed titles look like "Amazon Prime (Game, PC) - Some Game"
_TITLE_PREFIX_PATTERN = re.compile(r"^Amazon Prime \([^)]*\) - ")
_PRICE_LABEL = "Recommended price"

# ordered so "&amp;" is unescaped last and cannot double unescape
_XML_ENTITIES = {
    "&lt;": "<",
    "&gt;": ">",
    "&quot;": '"',
    "&apos;": "'",
    "&#039;": "'",
    "&#39;": "'",
    "&amp;": "&",
}


def fetch_amazon_game_offers() -> list[dict[str, str]]:
    response = request(AMAZON_GAMES_FEED_URL)
    if response.status != 200:
        raise RuntimeError(
            f"Received status code {response.status} from {AMAZON_GAMES_FEED_URL}"
        )
    return parse_amazon_game_feed(response.body)


def parse_amazon_game_feed(
    feed_xml: str, now: datetime | None = None
) -> list[dict[str, str]]:
    """Parse the lootscraper atom feed into deal keyword dicts."""
    now = now if now is not None else datetime.now()
    offers = []
    for entry_xml in _ENTRY_PATTERN.findall(feed_xml):
        offer = _parse_entry(entry_xml, now)
        if offer is not None:
            offers.append(offer)
    return offers


def _parse_entry(entry_xml: str, now: datetime) -> dict[str, str] | None:
    entry_id = _tag_text(entry_xml, "id")
    title = _unescape(_tag_text(entry_xml, "title"))
    link_match = _LINK_PATTERN.search(entry_xml)
    link = _unescape(link_match.group(1)) if link_match else ""
    if not entry_id or not title or not link:
        return None

    image_match = _IMG_PATTERN.search(entry_xml)
    image = _unescape(image_match.group(1)) if image_match else ""

    valid_from = ""
    valid_to = ""
    price = ""
    for item_xml in _LIST_ITEM_PATTERN.findall(entry_xml):
        # list items look like "<li><b>Offer valid to:</b> 2026-09-16 00:00</li>"
        item_text = _unescape(_TAG_PATTERN.sub("", item_xml))
        label, _, value = item_text.partition(":")
        label = label.strip()
        if label == "Offer valid to":
            valid_to = value.strip()
        elif label == "Offer valid from":
            valid_from = value.strip()
        elif label.startswith(_PRICE_LABEL):
            price = value.strip()
            # display the euro symbol instead of the currency code
            if price.endswith(" EUR"):
                price = price.removesuffix(" EUR") + "€"

    end = _parse_end_datetime(valid_to)
    if end is not None and end < now:
        # the feed keeps recent history, so skip offers that already ended
        return None

    return {
        "id": AMAZON_ID_PREFIX + entry_id.rstrip("/").split("/")[-1],
        "title": _TITLE_PREFIX_PATTERN.sub("", title).strip(),
        "worth": price if price else "N/A",
        "image": image,
        "open_giveaway_url": link,
        "published_date": valid_from if valid_from else "N/A",
        "end_date": _format_end_date(end),
        "status": "Active",
        "platforms": AMAZON_PLATFORM_NAME,
    }


def _tag_text(entry_xml: str, tag: str) -> str:
    match = re.search(rf"<{tag}[^>]*>(.*?)</{tag}>", entry_xml, re.DOTALL)
    return match.group(1).strip() if match else ""


def _unescape(text: str) -> str:
    for entity, character in _XML_ENTITIES.items():
        text = text.replace(entity, character)
    return text


def _parse_end_datetime(valid_to: str) -> datetime | None:
    try:
        end = datetime.strptime(valid_to, "%Y-%m-%d %H:%M")
    except ValueError:
        return None
    # offers ending exactly at midnight are last claimable the day before
    if end.hour == 0 and end.minute == 0:
        end -= timedelta(minutes=1)
    return end


def _format_end_date(end: datetime | None) -> str:
    return end.strftime("%Y-%m-%d") if end is not None else "N/A"
